name: blog-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - altair
  - seaborn
  - bokeh
  - ipykernel
  - jupyterlab
  - jupyter_contrib_nbextensions
  - scikit-learn
